repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.2  # pick the isort version you'd like to use from https://github.com/pre-commit/mirrors-isort/releases
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
